// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPpahZzlLXlXwFszRL6W8yzmsC7wfwTIk',
    appId: '1:118811838509:web:fd7a017d3658ba56cdd0a4',
    messagingSenderId: '118811838509',
    projectId: 'forum-backend-2e0f6',
    authDomain: 'forum-backend-2e0f6.firebaseapp.com',
    storageBucket: 'forum-backend-2e0f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCTemBibwbMKy8HbyYlFTlnaqg3HEXt7c',
    appId: '1:118811838509:android:bffb8403ab661e3fcdd0a4',
    messagingSenderId: '118811838509',
    projectId: 'forum-backend-2e0f6',
    storageBucket: 'forum-backend-2e0f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrvETZbzxkOQaby2kpIx43GfpkbU-e4lc',
    appId: '1:118811838509:ios:d7d796c96f311f07cdd0a4',
    messagingSenderId: '118811838509',
    projectId: 'forum-backend-2e0f6',
    storageBucket: 'forum-backend-2e0f6.appspot.com',
    iosClientId: '118811838509-htsugk5k4h5gmkifqobjc07a2u7t8klq.apps.googleusercontent.com',
    iosBundleId: 'productions.racler.christianflasskamp.forum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrvETZbzxkOQaby2kpIx43GfpkbU-e4lc',
    appId: '1:118811838509:ios:d7d796c96f311f07cdd0a4',
    messagingSenderId: '118811838509',
    projectId: 'forum-backend-2e0f6',
    storageBucket: 'forum-backend-2e0f6.appspot.com',
    iosClientId: '118811838509-htsugk5k4h5gmkifqobjc07a2u7t8klq.apps.googleusercontent.com',
    iosBundleId: 'productions.racler.christianflasskamp.forum',
  );
}
